### ISSUE TITLE
[BUG] Ethereum coins show error until pool is online. 

### ISSUE THREAD

**Issue by minernl** [minernl/miningcore#28]
Following error is shown in the console after starting the Pool with a Ethereum coin while generating DAG. The error is shown multiple times until DAG gen is completed and pool is online.
------------------------------------------------------------------------------------------------------------------------------
```
[2021-02-04 20:21:54.3695] [E] [ethereum] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.UpdateNetworkStatsAsync() in /opt/build/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumJobManager.cs:line 335 System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.UpdateNetworkStatsAsync() in /opt/build/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumJobManager.cs:line 335    at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.UpdateNetworkStatsAsync() in /opt/build/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumJobManager.cs:line 335
[2021-02-04 20:21:54.5503] [I] [ethereum] Loading current DAG ...
```
------------------------------------------------------------------------------------------------------------------------------

ERROR code: EthereumJobManager.cs
---------------------------------------------
```
// get sample block info (latestBlock-50)
ulong sampleBlockCount = 50;
var sampleBlockNumber = latestBlockHeight - sampleBlockCount;
var sampleBlockResults = await daemon.ExecuteCmdAllAsync<DaemonResponses.Block>(logger, EthCommands.GetBlockByNumber, new[] { (object) sampleBlockNumber, true });
var sampleBlockHeight = sampleBlockResults.First(x => x.Error == null && x.Response?.Height != null).Response.Height.Value;
var sampleBlockTimestamp = sampleBlockResults.First(x => x.Error == null && x.Response?.Height != null).Response.Timestamp;
```
------------------------------------------------------------------------------------------------------------------------------

**To Reproduce**
1. Start pool with Ethereum coin.

**Expected behavior**
No error

**System information:
 - OS: Ubuntu 20.04 
 - dotnet 3.1
 - Miningcore release v0.25

NOTE:
This error is given because the Network Stats can not execute eth_getBlockByNumber to report in the stats.
This is because the pool engine is not online jet and does not accept incoming requests.

-->> The error is NOT critical and is only related to stats info.  <<--

**Comment by Konstantin35** [comment]
incorrect `sampleBlockNumber` format

**Comment by minernl** [comment]
Konstantin35 you are right.
Code change fixes the error:
`var sampleBlockResults = await daemon.ExecuteCmdAllAsync<DaemonResponses.Block>(logger, EthCommands.GetBlockByNumber, new[] { (object) sampleBlockNumber.ToStringHexWithPrefix(), true });`

**Comment by minernl** [comment]
BugFix https://github.com/minernl/miningcore/commit/91c7e4055212668170e5c573d3980170c3b59a2f
