### ISSUE TITLE
The type initializer for 'ZeroMQ.lib.zmq' threw an exception

### ISSUE THREAD

**Issue by 5iwek** [minernl/miningcore#39]
Hey. I tried running minincore on Windows and Ubuntu, but the same error occured every time. (Vertcoin)

It just keeps spamming these errors.

```
[2021-03-19 20:15:14.2738] [I] [StatsRecorder] Starting Pool Stats Service 
[2021-03-19 20:15:14.2860] [I] [vtc1] Starting Pool ... 
[2021-03-19 20:15:14.2954] [I] [vtc1] Starting Job Manager ... 
[2021-03-19 20:15:14.4431] [I] [vtc1] All daemons online 
[2021-03-19 20:15:14.5267] [I] [vtc1] All daemons synched with blockchain 
[2021-03-19 20:15:14.6770] [I] [vtc1] Subscribing to ZMQ push-updates from (tcp://127.0.0.1:15101, hashblock) 
[2021-03-19 20:15:14.7180] [I] [vtc1] Job Manager Online 
[2021-03-19 20:15:14.8123] [E] [vtc1] System.TypeInitializationException: The type initializer for 'ZeroMQ.lib.zmq' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'ZeroMQ.ZSymbol' threw an exception.
 ---> System.FieldAccessException: Cannot set initonly static field 'EPERM' after type 'ZeroMQ.ZError' is initialized.
   at System.RuntimeFieldHandle.SetValue(RtFieldInfo field, Object obj, Object value, RuntimeType fieldType, FieldAttributes fieldAttr, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at ZeroMQ.ZSymbol.PickupConstantSymbols[T](IDictionary`2& symbols)
   at ZeroMQ.ZSymbol..cctor()
   --- End of inner exception stack trace ---
   at ZeroMQ.lib.zmq..cctor()
   --- End of inner exception stack trace ---
   at ZeroMQ.lib.zmq.ctx_new()
   at ZeroMQ.ZContext..ctor()
   at ZeroMQ.ZContext.get_Current()
   at Miningcore.DaemonInterface.DaemonClient.<>c__DisplayClass28_1.<ZmqSubscribeEndpoint>b__2() in /home/filip/Desktop/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 606 System.TypeInitializationException: The type initializer for 'ZeroMQ.lib.zmq' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'ZeroMQ.ZSymbol' threw an exception.
 ---> System.FieldAccessException: Cannot set initonly static field 'EPERM' after type 'ZeroMQ.ZError' is initialized.
   at System.RuntimeFieldHandle.SetValue(RtFieldInfo field, Object obj, Object value, RuntimeType fieldType, FieldAttributes fieldAttr, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at ZeroMQ.ZSymbol.PickupConstantSymbols[T](IDictionary`2& symbols)
   at ZeroMQ.ZSymbol..cctor()
   --- End of inner exception stack trace ---
   at ZeroMQ.lib.zmq..cctor()
   --- End of inner exception stack trace ---
   at ZeroMQ.lib.zmq.ctx_new()
   at ZeroMQ.ZContext..ctor()
   at ZeroMQ.ZContext.get_Current()
   at Miningcore.DaemonInterface.DaemonClient.<>c__DisplayClass28_1.<ZmqSubscribeEndpoint>b__2() in /home/filip/Desktop/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 606    at ZeroMQ.lib.zmq.ctx_new()
   at ZeroMQ.ZContext..ctor()
   at ZeroMQ.ZContext.get_Current()
   at Miningcore.DaemonInterface.DaemonClient.<>c__DisplayClass28_1.<ZmqSubscribeEndpoint>b__2() in /home/filip/Desktop/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 606
```

**Comment by leviable** [comment]
Comment out the zeroMQ line in your config.conf:
```
                    // "zmqBlockNotifySocket": "tcp://127.0.0.1:15101",
```

**Comment by 5iwek** [comment]
It worked! Thanks.
