### ISSUE TITLE
Bitcoin SV - crash on startup: Could not convert to integer 

### ISSUE THREAD

**Issue by mboyd1** [minernl/miningcore#56]
trying to startup miningcore, works fine on bitcoin BTC core but when I point it at a Bitcoin SV node, it crashes on startup consistently

> Miningcore - MinerNL build v2.0.0.0
Run location: /home/michael/git/miningcore/miningcore/build

Using configuration file config.json

Pool Configuration file is valid
[2022-05-16 19:16:40.9877] [I] [PoolCore] .NET Core 3.1.25 on Linux 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 [X64]
[2022-05-16 19:16:41.2332] [I] [Postgres] Connecting to Postgres Server 127.0.0.1:5432 Database=miningcore User=miningcore
[2022-05-16 19:16:41.3006] [I] [PoolCore] 94 coins loaded from /home/michael/git/miningcore/miningcore/build/coins.json
[2022-05-16 19:16:41.3323] [I] [ShareRecorder] Online
[2022-05-16 19:16:41.3593] [I] [Api] Starting API Service @ 127.0.0.1:4000  [rate-limiting disabled]
[2022-05-16 19:16:41.4079] [I] [Api] API Access to /api/admin restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2022-05-16 19:16:41.4079] [I] [Api] API Access to /metrics restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2022-05-16 19:16:41.4677] [I] [Api] API Online @ 127.0.0.1:4000  [rate-limiting disabled]
[2022-05-16 19:16:41.4677] [I] [Api] Prometheus Metrics Online @ 127.0.0.1:4000/metrics
[2022-05-16 19:16:41.4677] [I] [Api] WebSocket notifications streaming @ 127.0.0.1:4000/notifications
[2022-05-16 19:16:41.4732] [I] [StatsRecorder] Pool Stats Online
[2022-05-16 19:16:41.4758] [I] [PayoutManager] Starting Payout Manager
[2022-05-16 19:16:41.4758] [I] [StatsRecorder] Starting Pool Stats Service
[2022-05-16 19:16:41.4758] [I] [PayoutManager] Processing payments for pool [bsv1]
[2022-05-16 19:16:41.4823] [I] [bsv1] Starting Pool ...
[2022-05-16 19:16:41.4862] [I] [bsv1] Starting Job Manager ...
[2022-05-16 19:16:41.5354] [I] [bsv1] All daemons online
[2022-05-16 19:16:41.7584] [I] [PayoutManager] No updated blocks for pool bsv1
[2022-05-16 19:16:41.7636] [I] [PayoutManager] No balances over configured minimum payout for pool bsv1
[2022-05-16 19:16:47.3097] [I] [bsv1] Daemons still syncing with network. Manager will be started once synced
[2022-05-16 19:16:47.3347] [E] [bsv1] Newtonsoft.Json.JsonReaderException: Could not convert to integer: 1651050977967. Path '[57].timeoffset'.
 ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value, IFormatProvider provider)
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Miningcore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /home/michael/git/miningcore/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 469
   at Miningcore.DaemonInterface.DaemonClient.ExecuteCmdAnyAsync[TResponse](ILogger logger, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings, Boolean throwOnError) in /home/michael/git/miningcore/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 183
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.ShowDaemonSyncProgressAsync() in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 233
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.EnsureDaemonsSynchedAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 459
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 121
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 398
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Mining/PoolBase.cs:line 352 Newtonsoft.Json.JsonReaderException: Could not convert to integer: 1651050977967. Path '[57].timeoffset'.
 ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value, IFormatProvider provider)
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Miningcore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /home/michael/git/miningcore/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 469
   at Miningcore.DaemonInterface.DaemonClient.ExecuteCmdAnyAsync[TResponse](ILogger logger, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings, Boolean throwOnError) in /home/michael/git/miningcore/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 183
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.ShowDaemonSyncProgressAsync() in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 233
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.EnsureDaemonsSynchedAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 459
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 121
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 398
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Mining/PoolBase.cs:line 352    at Newtonsoft.Json.JsonReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Miningcore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /home/michael/git/miningcore/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 469
   at Miningcore.DaemonInterface.DaemonClient.ExecuteCmdAnyAsync[TResponse](ILogger logger, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings, Boolean throwOnError) in /home/michael/git/miningcore/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 183
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.ShowDaemonSyncProgressAsync() in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 233
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.EnsureDaemonsSynchedAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 459
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 121
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 398
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Mining/PoolBase.cs:line 352
System.AggregateException: One or more errors occurred. (Could not convert to integer: 1651050977967. Path '[57].timeoffset'.)
 ---> Newtonsoft.Json.JsonReaderException: Could not convert to integer: 1651050977967. Path '[57].timeoffset'.
 ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value, IFormatProvider provider)
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Miningcore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /home/michael/git/miningcore/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 469
   at Miningcore.DaemonInterface.DaemonClient.ExecuteCmdAnyAsync[TResponse](ILogger logger, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings, Boolean throwOnError) in /home/michael/git/miningcore/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 183
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.ShowDaemonSyncProgressAsync() in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 233
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.EnsureDaemonsSynchedAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 459
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 121
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 398
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in /home/michael/git/miningcore/miningcore/src/Miningcore/Mining/PoolBase.cs:line 352
   at Miningcore.PoolCore.Pool.<>c.<<StartMiningcorePoolServices>b__16_2>d.MoveNext() in /home/michael/git/miningcore/miningcore/src/Miningcore/PoolCore/PoolCore.cs:line 304
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.PoolCore.Pool.StartMiningcorePoolServices() in /home/michael/git/miningcore/miningcore/src/Miningcore/PoolCore/PoolCore.cs:line 288
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Miningcore.PoolCore.Pool.StartMiningCorePool(String configFile)
Cluster cannot start. Good Bye!
Miningcore is shuting down... bye!
[2022-05-16 19:16:47.3480] [I] [PoolCore] Miningcore is shuting down... bye!
Stopping pool Miningcore.Blockchain.Bitcoin.BitcoinPool
[2022-05-16 19:16:47.3480] [I] [ShareReceiver] Stopping ..
[2022-05-16 19:16:47.3503] [I] [ShareReceiver] Stopped
[2022-05-16 19:16:47.3503] [I] [ShareRecorder] Stopping ..
[2022-05-16 19:16:47.3503] [I] [ShareRecorder] Stopped
[2022-05-16 19:16:47.3503] [I] [StatsRecorder] Pool Stats Stopping ..
[2022-05-16 19:16:47.3503] [I] [StatsRecorder] Pool Stats Stopped
fish: Job 1, 'dotnet Miningcore.dll -c config…' terminated by signal SIGKILL (Forced quit)

**Comment by mboyd1** [comment]
tried it on older bitcoinsv-1.0.8 node and it works, so it's some kind of 32/64bit value change in the bsv node.  How can we get miningcore working on latest node for BSV?

**Comment by mboyd1** [comment]
not sure what the issue was but it does actually work on latest node, on testnet at least.  on mainnet it never starts up stratum and waits forever at "Daemon has downloaded 100.00% of blockchain"
